"""updated video progress model

Revision ID: 85369228fd47
Revises: d890706f2910
Create Date: 2025-12-20 13:28:54.969709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85369228fd47'
down_revision: Union[str, Sequence[str], None] = 'd890706f2910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_progress', sa.Column('watched', sa.Boolean(), nullable=True))
    op.add_column('video_progress', sa.Column('watch_date', sa.DateTime(), nullable=True))
    op.alter_column('video_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_progress', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_progress', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_video_progress_id'), 'video_progress', ['id'], unique=False)
    op.drop_column('video_progress', 'completed_at')
    op.drop_column('video_progress', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_progress', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('video_progress', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_video_progress_id'), table_name='video_progress')
    op.alter_column('video_progress', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_progress', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('video_progress', 'watch_date')
    op.drop_column('video_progress', 'watched')
    # ### end Alembic commands ###
