"""Add user bio and course second title

Revision ID: c2953ed2616b
Revises: 85369228fd47
Create Date: 2025-12-26 14:24:48.925612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2953ed2616b'
down_revision: Union[str, Sequence[str], None] = '85369228fd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('sub_title', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('headline', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'headline')
    op.drop_column('courses', 'sub_title')
    # ### end Alembic commands ###
